### ISSUE TITLE
message listener and monitoring portal code, installation scripts, and db table setup

### ISSUE THREAD

**Issue by jasonfleming** [renci-unc/asgs#2]
I'm wondering if the django code and db setup scripts for the monitoring portal, the message listener, and the associated db are in a repository. Will this infrastructure be posted to a github repo or kept offline?

**Comment by lstillwe** [comment]
Hi Jason - I sent you an invite to the repo in GitHub. It is private for now.

On Dec 14, 2018, at 5:50 PM, Jason Fleming <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm wondering if the django code and db setup scripts for the monitoring portal, the message listener, and the associated db are in a repository. Will this infrastructure be posted to a github repo or kept offline?

**Comment by jasonfleming** [comment]
Thank you Lisa!
